server:
  port: 10086

spring:
  datasource:
    url: jdbc:mysql://121.43.159.80:3306/erp?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0 #redis数据库索引，默认为0
    host: 121.43.159.80 #redis服务器地址
    port: 6379 #redis服务器连接端口
    password: #redis服务器连接密码，默认为null
    timeout: 5000 #redis连接超时时间
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations:classpath*:/mapper/**/*.xml
